spring:
  datasource:
    username: admin
    password: admin1234
#    url: jdbc:postgresql://localhost:5433/ClearSolutionDB
#    driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:ClearSolutionDB
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    drop-first: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  h2:
    console:
      enabled: true
validation:
  minAge: 18